In [2]:
import cv2
import numpy as np

In [3]:
img = cv2.imread('74707.jpg')

In [52]:
for x in range(100):
    for y in range(100):
        img.itemset((500+x,500+y,1),255)

In [60]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [54]:
print(img.shape)

(1062, 1600, 3)


In [56]:
print(img.size)

5097600


In [57]:
ball = img[280:340, 330:390]
img[273:333, 100:160] = ball

In [59]:
b,g,r = cv2.split(img)
img = cv2.merge((b,g,r))

In [64]:
print(r)

[[255 255 255 ...  41  43  45]
 [255 255 255 ...  41  43  45]
 [255 255 255 ...  42  43  44]
 ...
 [122 112 114 ...  88  88  90]
 [ 93  87  94 ...  97  97  98]
 [ 85  78  80 ...  95  98  99]]
