# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [25]:
l=1
kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]],np.float32)

In [26]:
kernel

array([[-1., -1., -1.],
       [-1.,  8., -1.],
       [-1., -1., -1.]], dtype=float32)

In [27]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [28]:
img

array([[8, 8, 2, 4, 2, 0, 2, 3, 0, 8, 8, 6],
       [4, 5, 7, 2, 6, 6, 0, 2, 5, 0, 1, 7],
       [6, 2, 5, 2, 6, 4, 4, 6, 9, 7, 0, 9],
       [5, 8, 3, 5, 1, 7, 4, 9, 3, 8, 7, 2],
       [7, 6, 2, 1, 2, 7, 5, 3, 1, 3, 6, 1],
       [9, 4, 5, 7, 9, 1, 0, 1, 4, 3, 0, 6],
       [5, 2, 4, 5, 4, 4, 3, 1, 5, 0, 8, 2],
       [8, 9, 2, 3, 4, 3, 0, 9, 5, 1, 8, 9],
       [2, 4, 4, 4, 5, 2, 2, 1, 2, 7, 9, 5],
       [8, 4, 8, 7, 7, 7, 8, 7, 0, 8, 0, 0],
       [4, 8, 3, 3, 7, 5, 9, 4, 0, 7, 2, 8],
       [4, 8, 7, 2, 7, 9, 9, 3, 5, 2, 9, 5]])

In [29]:
h,w=img.shape

In [30]:
print(h,w)

12 12


In [31]:
#[*range(-2,3)]
dst = np.zeros((h,w),np.int)

C:\Users\82108\AppData\Local\Temp\ipykernel_22828\473154620.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [32]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [33]:
img

array([[8, 8, 2, 4, 2, 0, 2, 3, 0, 8, 8, 6],
       [4, 5, 7, 2, 6, 6, 0, 2, 5, 0, 1, 7],
       [6, 2, 5, 2, 6, 4, 4, 6, 9, 7, 0, 9],
       [5, 8, 3, 5, 1, 7, 4, 9, 3, 8, 7, 2],
       [7, 6, 2, 1, 2, 7, 5, 3, 1, 3, 6, 1],
       [9, 4, 5, 7, 9, 1, 0, 1, 4, 3, 0, 6],
       [5, 2, 4, 5, 4, 4, 3, 1, 5, 0, 8, 2],
       [8, 9, 2, 3, 4, 3, 0, 9, 5, 1, 8, 9],
       [2, 4, 4, 4, 5, 2, 2, 1, 2, 7, 9, 5],
       [8, 4, 8, 7, 7, 7, 8, 7, 0, 8, 0, 0],
       [4, 8, 3, 3, 7, 5, 9, 4, 0, 7, 2, 8],
       [4, 8, 7, 2, 7, 9, 9, 3, 5, 2, 9, 5]])

In [34]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  -2,  26, -18,  22,  24, -27, -13,   5, -38, -37,   0],
       [  0, -27,   6, -19,  15,  -2,  -6,  12,  32,  23, -41,   0],
       [  0,  28,  -7,  18, -26,  23, -13,  37, -22,  28,  20,   0],
       [  0,   5, -23, -26, -22,  27,   8,  -3, -26,  -8,  18,   0],
       [  0,  -8,   9,  24,  41, -26, -25, -14,  15,  -3, -29,   0],
       [  0, -30,  -5,   2,  -4,   8,   5, -19,  16, -34,  35,   0],
       [  0,  41, -19,  -8,   2,   0, -25,  53,  14, -36,  23,   0],
       [  0, -13,  -9,  -8,   3, -20, -21, -25, -22,  23,  34,   0],
       [  0,  -9,  27,  15,  16,  11,  27,  30, -36,  37, -46,   0],
       [  0,  18, -23, -24,   9, -23,  20,  -9, -36,  30, -23,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [35]:
img = cv2.imread('lenna.png', 0)

In [36]:
h,w=img.shape

In [37]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [38]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [40]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()