# 1.4.4 Smoothing Images

## Kernel Convolution

In [2]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [3]:
l=1
kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]],np.float32)

In [4]:
kernel

array([[-1., -1., -1.],
       [-1.,  8., -1.],
       [-1., -1., -1.]], dtype=float32)

In [5]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [6]:
img

array([[7, 2, 3, 0, 6, 0, 9, 9, 2, 5, 5, 4],
       [8, 8, 8, 8, 1, 7, 5, 6, 5, 9, 1, 4],
       [6, 7, 4, 0, 2, 8, 6, 4, 2, 5, 9, 1],
       [0, 8, 8, 0, 4, 9, 6, 5, 2, 6, 7, 6],
       [4, 6, 9, 5, 4, 3, 5, 7, 9, 6, 8, 4],
       [7, 3, 9, 6, 7, 5, 4, 7, 5, 1, 0, 0],
       [6, 5, 5, 9, 7, 1, 6, 8, 4, 5, 9, 1],
       [9, 1, 5, 2, 8, 0, 3, 9, 1, 7, 3, 5],
       [4, 8, 1, 7, 4, 6, 7, 7, 4, 9, 5, 4],
       [1, 5, 4, 4, 4, 6, 8, 1, 6, 3, 3, 4],
       [1, 1, 0, 2, 5, 0, 3, 8, 3, 8, 9, 9],
       [9, 2, 9, 3, 0, 6, 7, 9, 7, 5, 3, 7]])

In [7]:
h,w=img.shape

In [8]:
print(h,w)

12 12


In [9]:
#[*range(-2,3)]
dst = np.zeros((h,w),np.int)

C:\Users\82108\AppData\Local\Temp\ipykernel_13500\473154620.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[7, 2, 3, 0, 6, 0, 9, 9, 2, 5, 5, 4],
       [8, 8, 8, 8, 1, 7, 5, 6, 5, 9, 1, 4],
       [6, 7, 4, 0, 2, 8, 6, 4, 2, 5, 9, 1],
       [0, 8, 8, 0, 4, 9, 6, 5, 2, 6, 7, 6],
       [4, 6, 9, 5, 4, 3, 5, 7, 9, 6, 8, 4],
       [7, 3, 9, 6, 7, 5, 4, 7, 5, 1, 0, 0],
       [6, 5, 5, 9, 7, 1, 6, 8, 4, 5, 9, 1],
       [9, 1, 5, 2, 8, 0, 3, 9, 1, 7, 3, 5],
       [4, 8, 1, 7, 4, 6, 7, 7, 4, 9, 5, 4],
       [1, 5, 4, 4, 4, 6, 8, 1, 6, 3, 3, 4],
       [1, 1, 0, 2, 5, 0, 3, 8, 3, 8, 9, 9],
       [9, 2, 9, 3, 0, 6, 7, 9, 7, 5, 3, 7]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  19,  32,  40, -23,  19,  -9,   6,  -2,  38, -34,   0],
       [  0,   6, -15, -35, -21,  24,  -2,  -5, -26,  -1,  33,   0],
       [  0,  20,  25, -36,   1,  34,   1,  -1, -28,   0,  11,   0],
       [  0,   0,  27,  -7,  -7, -20,  -6,  13,  33,  10,  34,   0],
       [  0, -27,  24,  -7,  16,   3, -10,   8,  -7, -38, -34,   0],
       [  0,  -5,   0,  23,  18, -32,  11,  25, -11,  10,  50,   0],
       [  0, -35,   2, -30,  28, -42, -20,  32, -45,  16, -21,   0],
       [  0,  34, -28,  24,  -5,   8,  16,  17, -11,  40,   2,   0],
       [  0,  20,   4,   5,  -2,  11,  26, -38,   5, -23, -27,   0],
       [  0, -23, -30, -13,  15, -39, -21,  20, -23,  25,  30,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lenna.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()